In [2]:
import numpy as np
from scipy.spatial.distance import cdist

# --- Copy lại các hàm đã cài đặt ở Bài 1 ---

def kmeans_init_centers(X, n_cluster):
    # Khởi tạo ngẫu nhiên n_cluster tâm cụm không trùng lặp từ bộ dữ liệu X
    return X[np.random.choice(X.shape[0], n_cluster, replace=False)]

def kmeans_predict_labels(X, centers):
    # Tính ma trận khoảng cách Euclid giữa toàn bộ điểm dữ liệu X và các tâm cụm centers
    D = cdist(X, centers)
    # Trả về chỉ số (index) của tâm cụm gần nhất cho từng điểm dữ liệu
    return np.argmin(D, axis=1)

def kmeans_update_centers(X, labels, n_cluster):
    # Cập nhật lại vị trí các tâm cụm bằng cách lấy trung bình cộng tọa độ của các điểm thuộc cụm đó
    centers = np.zeros((n_cluster, X.shape[1]))
    for k in range(n_cluster):
        Xk = X[labels == k, :]
        if len(Xk) > 0:
            centers[k, :] = np.mean(Xk, axis=0)
    return centers

def kmeans_has_converged(centers, new_centers):
    # Trả về True nếu tập hợp các tâm cụm mới trùng khớp hoàn toàn với tập hợp tâm cụm cũ
    return (set([tuple(a) for a in centers]) == set([tuple(a) for a in new_centers]))

def fit_kmeans(X, n_cluster, max_iters=100):
    print("Khởi đầu thuật toán K-Means...")
    centers = kmeans_init_centers(X, n_cluster)
    print(f"Tâm cụm khởi tạo ngẫu nhiên ban đầu:\n{centers}\n")

    labels = np.zeros(X.shape[0])

    for i in range(max_iters):
        print(f"--- VÒNG LẶP THỨ {i + 1} ---")

        # Bước 1: Gán nhãn cho các điểm dựa vào tâm hiện tại
        labels = kmeans_predict_labels(X, centers)
        print(f"Nhãn của các điểm dữ liệu sau khi gán: {labels}")

        # Bước 2: Cập nhật lại vị trí tâm cụm
        new_centers = kmeans_update_centers(X, labels, n_cluster)
        print(f"Vị trí tâm cụm mới sau khi cập nhật:\n{new_centers}")

        # Bước 3: Kiểm tra điều kiện dừng hội tụ
        if kmeans_has_converged(centers, new_centers):
            print("\n==> Thuật toán ĐÃ HỘI TỤ! (Các tâm cụm không còn thay đổi vị trí).")
            break
        else:
            print("==> Thuật toán CHƯA HỘI TỤ, tiếp tục vòng lặp tiếp theo.\n")

        centers = new_centers

    return centers, labels

# --- Tiến hành chạy thử nghiệm dữ liệu ---
if __name__ == "__main__":
    # Khởi tạo 6 điểm dữ liệu (Chia rõ rệt làm 2 nhóm)
    X_test = np.array([
        [1.0, 2.0],
        [2.0, 1.0],
        [3.0, 1.0],
        [6.0, 7.0],
        [7.0, 6.0],
        [8.0, 8.0]
    ])

    # Chạy thuật toán gom làm 2 cụm
    final_centers, final_labels = fit_kmeans(X_test, n_cluster=2)

    print("\n================ KẾT QUẢ CUỐI CÙNG ================")
    print("Tọa độ các tâm cụm tối ưu tìm được:")
    for idx, center in enumerate(final_centers):
        print(f" Tâm cụm {idx}: {center}")
    print(f"Mảng nhãn phân cụm của 6 điểm dữ liệu tương ứng: {final_labels}")

Khởi đầu thuật toán K-Means...
Tâm cụm khởi tạo ngẫu nhiên ban đầu:
[[3. 1.]
 [7. 6.]]

--- VÒNG LẶP THỨ 1 ---
Nhãn của các điểm dữ liệu sau khi gán: [0 0 0 1 1 1]
Vị trí tâm cụm mới sau khi cập nhật:
[[2.         1.33333333]
 [7.         7.        ]]
==> Thuật toán CHƯA HỘI TỤ, tiếp tục vòng lặp tiếp theo.

--- VÒNG LẶP THỨ 2 ---
Nhãn của các điểm dữ liệu sau khi gán: [0 0 0 1 1 1]
Vị trí tâm cụm mới sau khi cập nhật:
[[2.         1.33333333]
 [7.         7.        ]]

==> Thuật toán ĐÃ HỘI TỤ! (Các tâm cụm không còn thay đổi vị trí).

================ KẾT QUẢ CUỐI CÙNG ================
Tọa độ các tâm cụm tối ưu tìm được:
 Tâm cụm 0: [2.         1.33333333]
 Tâm cụm 1: [7. 7.]
Mảng nhãn phân cụm của 6 điểm dữ liệu tương ứng: [0 0 0 1 1 1]
